// Run: node scripts/make-voiceover.ts [--samples] [--force]
// Generates one clip per line of src/voiceover.ts with fal.ai (ElevenLabs Eleven v4 by default) into
// public/voiceover/, measures each clip, flags lines that would run into the next one, and writes
// src/voiceover.generated.ts (durations) for the soundtrack's music ducking.
// Needs FAL_KEY in video/.env (gitignored). Optional in .env: FAL_VOICE (default Sarah), FAL_TTS_MODEL.
// --samples renders one line in four warm female voices into public/voiceover/samples/ to pick from.
// Unchanged lines are skipped, so re-runs only spend credits on edits.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { VO_LINES } from '../src/voiceover.ts';

const root = new URL('..', import.meta.url);
const envFile = new URL('.env', root);
const env: Record<string, string> = { ...(process.env as Record<string, string>) };
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
const key: string = env.FAL_KEY ?? env.FAL_API_KEY ?? '';
if (!key) {
  console.error('Missing FAL_KEY. Add it to video/.env as FAL_KEY=... and run again.');
  process.exit(1);
}
const MODEL = env.FAL_TTS_MODEL || 'elevenlabs/tts/eleven-v4';
const VOICE = env.FAL_VOICE || 'Sarah';
const VIDEO_SECONDS = 84;
// Eleven v4 takes no previous/next text, so a fixed seed and one stability keep the read consistent across lines.
const SETTINGS = { stability: 0.6, similarity_boost: 0.75, seed: 7, language_code: 'en', output_format: 'mp3_44100_128' };

async function tts(text: string, voice: string): Promise<Buffer> {
  const res = await fetch(`https://fal.run/${MODEL}`, {
    method: 'POST',
    headers: { Authorization: `Key ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ text, voice, ...SETTINGS }),
  });
  if (!res.ok) {
    console.error(`fal ${MODEL} failed: ${res.status} ${(await res.text()).slice(0, 300)}`);
    process.exit(1);
  }
  const { audio } = (await res.json()) as { audio?: { url?: string } };
  if (!audio?.url) {
    console.error('fal returned no audio url');
    process.exit(1);
  }
  const file = await fetch(audio.url);
  if (!file.ok) {
    console.error(`audio download failed: ${file.status}`);
    process.exit(1);
  }
  return Buffer.from(await file.arrayBuffer());
}

const seconds = (file: URL): number =>
  Number.parseFloat(
    execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', fileURLToPath(file)]).toString(),
  );

const outDir = new URL('public/voiceover/', root);
mkdirSync(outDir, { recursive: true });

if (process.argv.includes('--samples')) {
  const sampleDir = new URL('samples/', outDir);
  mkdirSync(sampleDir, { recursive: true });
  const line = VO_LINES.find((l) => l.id === 'vo-08') ?? VO_LINES[0];
  for (const voice of ['Sarah', 'Rachel', 'Matilda', 'Alice']) {
    const file = new URL(`${voice}.mp3`, sampleDir);
    writeFileSync(file, await tts(line.text, voice));
    console.log(`${voice}: ${fileURLToPath(file)} (${seconds(file).toFixed(2)} s)`);
  }
  console.log('Pick one, set FAL_VOICE=<name> in video/.env, then run without --samples.');
  process.exit(0);
}

const force = process.argv.includes('--force');
const manifestFile = new URL('manifest.json', outDir);
const prev = existsSync(manifestFile)
  ? (JSON.parse(readFileSync(manifestFile, 'utf8')) as { voice: string; model: string; lines: Record<string, string> })
  : { voice: '', model: '', lines: {} as Record<string, string> };
console.log(`voice: ${VOICE}, model: ${MODEL}`);

const durations: Record<string, number> = {};
for (const line of VO_LINES) {
  const file = new URL(`${line.id}.mp3`, outDir);
  const unchanged =
    !force && existsSync(file) && prev.voice === VOICE && prev.model === MODEL && prev.lines[line.id] === line.text;
  if (!unchanged) writeFileSync(file, await tts(line.text, VOICE));
  durations[line.id] = Math.round(seconds(file) * 1000) / 1000;
}

// Overrun check: each clip must end 0.25 s before the next line (or before the video ends).
let overruns = 0;
for (const [i, line] of VO_LINES.entries()) {
  const end = line.at + durations[line.id];
  const limit = (VO_LINES[i + 1]?.at ?? VIDEO_SECONDS) - 0.25;
  if (end > limit) overruns++;
  console.log(
    `${line.id}  ${line.at.toFixed(1).padStart(5)}s  ${durations[line.id].toFixed(2)}s  ends ${end.toFixed(2)}  ${end <= limit ? 'ok' : `OVERRUN by ${(end - limit).toFixed(2)}s`}`,
  );
}

writeFileSync(
  manifestFile,
  `${JSON.stringify({ voice: VOICE, model: MODEL, lines: Object.fromEntries(VO_LINES.map((l) => [l.id, l.text])) }, null, 2)}\n`,
);
writeFileSync(
  new URL('src/voiceover.generated.ts', root),
  `// Generated by scripts/make-voiceover.ts: clip length in seconds per line. Do not edit.\nexport const VO_DURATIONS: Record<string, number> = ${JSON.stringify(durations, null, 2)};\n`,
);
console.log(overruns ? `${overruns} line(s) overrun: shorten the text or move the next line.` : 'all lines fit');
process.exit(overruns ? 2 : 0);
