// Generated by scripts/make-voiceover.ts: clip length in seconds per line. Do not edit.
export const VO_DURATIONS: Record<string, number> = {
  "vo-01": 3.553,
  "vo-02": 2.508,
  "vo-03": 3.396,
  "vo-04": 3.239,
  "vo-05": 2.116,
  "vo-06": 2.194,
  "vo-07": 3.004,
  "vo-08": 7.236,
  "vo-09": 7.706,
  "vo-10": 6.766,
  "vo-11": 4.284,
  "vo-12": 2.351,
  "vo-13": 3.396,
  "vo-14": 6.844,
  "vo-15": 5.799
};
